// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: api/strata.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_strata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_strata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetExRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExRequest) Reset() {
	*x = SetExRequest{}
	mi := &file_api_strata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExRequest) ProtoMessage() {}

func (x *SetExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExRequest.ProtoReflect.Descriptor instead.
func (*SetExRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{2}
}

func (x *SetExRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetExRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetExRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SetExResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExResponse) Reset() {
	*x = SetExResponse{}
	mi := &file_api_strata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExResponse) ProtoMessage() {}

func (x *SetExResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExResponse.ProtoReflect.Descriptor instead.
func (*SetExResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{3}
}

func (x *SetExResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_strata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_strata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_api_strata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{6}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_api_strata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{7}
}

func (x *DelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushRequest) Reset() {
	*x = ListPushRequest{}
	mi := &file_api_strata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushRequest) ProtoMessage() {}

func (x *ListPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushRequest.ProtoReflect.Descriptor instead.
func (*ListPushRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{8}
}

func (x *ListPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListPushRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushResponse) Reset() {
	*x = ListPushResponse{}
	mi := &file_api_strata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushResponse) ProtoMessage() {}

func (x *ListPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushResponse.ProtoReflect.Descriptor instead.
func (*ListPushResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{9}
}

func (x *ListPushResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ListPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopRequest) Reset() {
	*x = ListPopRequest{}
	mi := &file_api_strata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopRequest) ProtoMessage() {}

func (x *ListPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopRequest.ProtoReflect.Descriptor instead.
func (*ListPopRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{10}
}

func (x *ListPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopResponse) Reset() {
	*x = ListPopResponse{}
	mi := &file_api_strata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopResponse) ProtoMessage() {}

func (x *ListPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopResponse.ProtoReflect.Descriptor instead.
func (*ListPopResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{11}
}

func (x *ListPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DocSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocSetRequest) Reset() {
	*x = DocSetRequest{}
	mi := &file_api_strata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSetRequest) ProtoMessage() {}

func (x *DocSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSetRequest.ProtoReflect.Descriptor instead.
func (*DocSetRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{12}
}

func (x *DocSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocSetRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DocSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocSetResponse) Reset() {
	*x = DocSetResponse{}
	mi := &file_api_strata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSetResponse) ProtoMessage() {}

func (x *DocSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSetResponse.ProtoReflect.Descriptor instead.
func (*DocSetResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{13}
}

func (x *DocSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DocGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocGetRequest) Reset() {
	*x = DocGetRequest{}
	mi := &file_api_strata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocGetRequest) ProtoMessage() {}

func (x *DocGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocGetRequest.ProtoReflect.Descriptor instead.
func (*DocGetRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{14}
}

func (x *DocGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocGetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DocGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocGetResponse) Reset() {
	*x = DocGetResponse{}
	mi := &file_api_strata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocGetResponse) ProtoMessage() {}

func (x *DocGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocGetResponse.ProtoReflect.Descriptor instead.
func (*DocGetResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{15}
}

func (x *DocGetResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *DocGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DocDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocDelRequest) Reset() {
	*x = DocDelRequest{}
	mi := &file_api_strata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocDelRequest) ProtoMessage() {}

func (x *DocDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocDelRequest.ProtoReflect.Descriptor instead.
func (*DocDelRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{16}
}

func (x *DocDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DocDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocDelResponse) Reset() {
	*x = DocDelResponse{}
	mi := &file_api_strata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocDelResponse) ProtoMessage() {}

func (x *DocDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocDelResponse.ProtoReflect.Descriptor instead.
func (*DocDelResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{17}
}

func (x *DocDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MutationKey   string                 `protobuf:"bytes,1,opt,name=mutationKey,proto3" json:"mutationKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_strata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{18}
}

func (x *StreamRequest) GetMutationKey() string {
	if x != nil {
		return x.MutationKey
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_api_strata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_api_strata_proto_rawDescGZIP(), []int{19}
}

func (x *StreamResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *StreamResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StreamResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_strata_proto protoreflect.FileDescriptor

const file_api_strata_proto_rawDesc = "" +
	"\n" +
	"\x10api/strata.proto\x12\x06Strata\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\fSetExRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\")\n" +
	"\rSetExResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\vDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x0fListPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"*\n" +
	"\x10ListPushResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\"\"\n" +
	"\x0eListPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"A\n" +
	"\x0fListPopResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"5\n" +
	"\rDocSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"*\n" +
	"\x0eDocSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\rDocGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\":\n" +
	"\x0eDocGetResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"!\n" +
	"\rDocDelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDocDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\rStreamRequest\x12 \n" +
	"\vmutationKey\x18\x01 \x01(\tR\vmutationKey\"\x80\x01\n" +
	"\x0eStreamResponse\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion2\xa3\x05\n" +
	"\x06Strata\x12.\n" +
	"\x03Set\x12\x12.Strata.SetRequest\x1a\x13.Strata.SetResponse\x12.\n" +
	"\x03Get\x12\x12.Strata.GetRequest\x1a\x13.Strata.GetResponse\x12.\n" +
	"\x03Del\x12\x12.Strata.DelRequest\x1a\x13.Strata.DelResponse\x124\n" +
	"\x05SetEx\x12\x14.Strata.SetExRequest\x1a\x15.Strata.SetExResponse\x12:\n" +
	"\x05LPush\x12\x17.Strata.ListPushRequest\x1a\x18.Strata.ListPushResponse\x127\n" +
	"\x04LPop\x12\x16.Strata.ListPopRequest\x1a\x17.Strata.ListPopResponse\x12:\n" +
	"\x05RPush\x12\x17.Strata.ListPushRequest\x1a\x18.Strata.ListPushResponse\x127\n" +
	"\x04RPop\x12\x16.Strata.ListPopRequest\x1a\x17.Strata.ListPopResponse\x127\n" +
	"\x06DocSet\x12\x15.Strata.DocSetRequest\x1a\x16.Strata.DocSetResponse\x127\n" +
	"\x06DocGet\x12\x15.Strata.DocGetRequest\x1a\x16.Strata.DocGetResponse\x127\n" +
	"\x06DocDel\x12\x15.Strata.DocDelRequest\x1a\x16.Strata.DocDelResponse\x12>\n" +
	"\vXReadStream\x12\x15.Strata.StreamRequest\x1a\x16.Strata.StreamResponse0\x01B\x10Z\x0estrata/api;apib\x06proto3"

var (
	file_api_strata_proto_rawDescOnce sync.Once
	file_api_strata_proto_rawDescData []byte
)

func file_api_strata_proto_rawDescGZIP() []byte {
	file_api_strata_proto_rawDescOnce.Do(func() {
		file_api_strata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_strata_proto_rawDesc), len(file_api_strata_proto_rawDesc)))
	})
	return file_api_strata_proto_rawDescData
}

var file_api_strata_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_strata_proto_goTypes = []any{
	(*SetRequest)(nil),       // 0: Strata.SetRequest
	(*SetResponse)(nil),      // 1: Strata.SetResponse
	(*SetExRequest)(nil),     // 2: Strata.SetExRequest
	(*SetExResponse)(nil),    // 3: Strata.SetExResponse
	(*GetRequest)(nil),       // 4: Strata.GetRequest
	(*GetResponse)(nil),      // 5: Strata.GetResponse
	(*DelRequest)(nil),       // 6: Strata.DelRequest
	(*DelResponse)(nil),      // 7: Strata.DelResponse
	(*ListPushRequest)(nil),  // 8: Strata.ListPushRequest
	(*ListPushResponse)(nil), // 9: Strata.ListPushResponse
	(*ListPopRequest)(nil),   // 10: Strata.ListPopRequest
	(*ListPopResponse)(nil),  // 11: Strata.ListPopResponse
	(*DocSetRequest)(nil),    // 12: Strata.DocSetRequest
	(*DocSetResponse)(nil),   // 13: Strata.DocSetResponse
	(*DocGetRequest)(nil),    // 14: Strata.DocGetRequest
	(*DocGetResponse)(nil),   // 15: Strata.DocGetResponse
	(*DocDelRequest)(nil),    // 16: Strata.DocDelRequest
	(*DocDelResponse)(nil),   // 17: Strata.DocDelResponse
	(*StreamRequest)(nil),    // 18: Strata.StreamRequest
	(*StreamResponse)(nil),   // 19: Strata.StreamResponse
}
var file_api_strata_proto_depIdxs = []int32{
	0,  // 0: Strata.Strata.Set:input_type -> Strata.SetRequest
	4,  // 1: Strata.Strata.Get:input_type -> Strata.GetRequest
	6,  // 2: Strata.Strata.Del:input_type -> Strata.DelRequest
	2,  // 3: Strata.Strata.SetEx:input_type -> Strata.SetExRequest
	8,  // 4: Strata.Strata.LPush:input_type -> Strata.ListPushRequest
	10, // 5: Strata.Strata.LPop:input_type -> Strata.ListPopRequest
	8,  // 6: Strata.Strata.RPush:input_type -> Strata.ListPushRequest
	10, // 7: Strata.Strata.RPop:input_type -> Strata.ListPopRequest
	12, // 8: Strata.Strata.DocSet:input_type -> Strata.DocSetRequest
	14, // 9: Strata.Strata.DocGet:input_type -> Strata.DocGetRequest
	16, // 10: Strata.Strata.DocDel:input_type -> Strata.DocDelRequest
	18, // 11: Strata.Strata.XReadStream:input_type -> Strata.StreamRequest
	1,  // 12: Strata.Strata.Set:output_type -> Strata.SetResponse
	5,  // 13: Strata.Strata.Get:output_type -> Strata.GetResponse
	7,  // 14: Strata.Strata.Del:output_type -> Strata.DelResponse
	3,  // 15: Strata.Strata.SetEx:output_type -> Strata.SetExResponse
	9,  // 16: Strata.Strata.LPush:output_type -> Strata.ListPushResponse
	11, // 17: Strata.Strata.LPop:output_type -> Strata.ListPopResponse
	9,  // 18: Strata.Strata.RPush:output_type -> Strata.ListPushResponse
	11, // 19: Strata.Strata.RPop:output_type -> Strata.ListPopResponse
	13, // 20: Strata.Strata.DocSet:output_type -> Strata.DocSetResponse
	15, // 21: Strata.Strata.DocGet:output_type -> Strata.DocGetResponse
	17, // 22: Strata.Strata.DocDel:output_type -> Strata.DocDelResponse
	19, // 23: Strata.Strata.XReadStream:output_type -> Strata.StreamResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_strata_proto_init() }
func file_api_strata_proto_init() {
	if File_api_strata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_strata_proto_rawDesc), len(file_api_strata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_strata_proto_goTypes,
		DependencyIndexes: file_api_strata_proto_depIdxs,
		MessageInfos:      file_api_strata_proto_msgTypes,
	}.Build()
	File_api_strata_proto = out.File
	file_api_strata_proto_goTypes = nil
	file_api_strata_proto_depIdxs = nil
}
